### ISSUE TITLE
This is a RAT!

### ISSUE THREAD

**Issue by Erisfiregamer1** [l4tt/uwp-update-bypass#15]
Cerealwithnomilk hasn't released a new version of Fluster! The one you are giving is a RAT from Rune.

More information: https://www.reddit.com/r/robloxhackers/comments/17j3ftp/do_not_download_the_fluster/

>:/

**Comment by 2RichDudes** [comment]
![fluster works](https://github.com/l4tt/uwp-update-bypass/assets/149326603/9d602524-5226-4235-bb12-024554f7da7f)
![image](https://github.com/l4tt/uwp-update-bypass/assets/149326603/1499bfef-75dc-4540-8fb8-f50378b2cffb)
works for me.

**Comment by falixfresh** [comment]
I looked through all my startup through the program, but I didn’t find anything similar with rat

**Comment by falixfresh** [comment]
no proof

**Comment by Erisfiregamer1** [comment]
<img width="711" alt="image" src="https://github.com/l4tt/uwp-update-bypass/assets/54373833/64f4765e-f9b0-4cd4-aa17-372e296470a3">

This is straight from the official dev of Fluster.
At this point I have genuinely no idea if the new version is a RAT. I'd analyze it myself but I'm shit at that.

Can someone please go and check for me? According to robloxhackers, the modified version has a webhook that logs your data or something

**Comment by Pixeluted** [comment]
You can literally check the code by yourself, this is not a rat.

**Comment by Erisfiregamer1** [comment]
I'm not saying your app is a RAT, I'm saying the version of Fluster you're shipping *might* be.

**Comment by Pixeluted** [comment]
Confirmed by cereal that it is safe 
![image](https://github.com/l4tt/uwp-update-bypass/assets/78791776/a841906d-90d7-4221-8200-a262d9355be4)
![image](https://github.com/l4tt/uwp-update-bypass/assets/78791776/412044f5-21a1-47cc-8e1a-48843178ca99)

**Comment by Erisfiregamer1** [comment]
Huh, so it wasn't a RAT. I'll update my guide to include your tool, then.
