### ISSUE TITLE
Fluster installation error. [ RESOLVED ]

### ISSUE THREAD

**Issue by Aidan2662** [l4tt/uwp-update-bypass#16]
Whenever installing fluster with dev mode enabled, this error is shown: Add-AppxPackage : Deployment failed with HRESULT: 0x80073D2B, The package deployment failed because its content is not
valid for an unsigned package.
Windows cannot install package ROBLOXCORPORATION.FLUSTER because an unsigned package cannot include Executable
activations.
NOTE: For additional information, look for [ActivityId] ba0028ca-0aa9-0002-e759-00baa90ada01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID ba0028ca-0aa9-0002-e759-00baa90ada01
At line:1 char:1
+ Add-AppxPackage -path 'C:\Fluster\AppxManifest.xml' -register
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Fluster\AppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by V-ha** [comment]
Open Windows Powershell as Administrator and paste in the code ->
Code: `Get-AppxPackage -allusers ROBLOXCORPORATION.FLUSTER | Remove-AppxPackage`

**Comment by Aidan2662** [comment]
Get-AppxPackage : Access is denied.
Access is denied.

**Comment by V-ha** [comment]
Remove Previous Fluster Files and APP -> Go to your local disk and remove the fluster folder, then search for the fluster app and uninstal it.

**Comment by Aidan2662** [comment]
Successfully uninstalled

**Comment by V-ha** [comment]
Now Re-Install with Developer Mode Enabled

**Comment by Aidan2662** [comment]
Alright. Installing now.

**Comment by Aidan2662** [comment]
Thanks. Issue is resolved.

**Comment by V-ha** [comment]
You're welcome.
